import fs from'node:fs/promises';import{chromium}from'playwright';
const manifest=JSON.parse(await fs.readFile('evidence/manifest.json','utf8'));await fs.mkdir('evidence/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader']});const results=[];
for(const width of[1440,390]){const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:1});
for(const p of manifest.pages.slice(0,7)){const page=await context.newPage();const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText}));await page.goto('http://127.0.0.1:4173'+p.path,{waitUntil:'domcontentloaded'});await page.waitForTimeout(2500);
const popupClose=page.locator('.sgpb-popup-close-button-1');if(await popupClose.isVisible().catch(()=>false))await popupClose.click();
await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=650){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,80));}window.scrollTo(0,0);});await page.waitForTimeout(500);
await page.screenshot({path:`evidence/screenshots/${p.key}-${width}.png`,fullPage:true});
const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.body.scrollHeight,title:document.title,images:[...document.images].filter(i=>i.offsetWidth>0&&!i.complete||i.offsetWidth>0&&i.naturalWidth===0).map(i=>i.src),visibleMainText:document.querySelector('#main')?.innerText.length,kanit:[...document.querySelectorAll('#main p,#main h2')].filter(e=>e.offsetWidth>0).every(e=>getComputedStyle(e).fontFamily.includes('Kanit')),coin:!!document.querySelector('.blu-coin-ready')}));
let accordion=null;if(p.path==='/faq/'){const title=page.locator('.wdt-accordion-toggle-title-holder').first();if(await title.count()){await title.click();await page.waitForTimeout(250);accordion=await title.evaluate(e=>({class:e.className,parent:e.parentElement.className}));}}
results.push({path:p.path,width,metrics,errors,failed,accordion});console.log(p.path,width,metrics.height,'overflow',metrics.scrollWidth-width,'errors',errors.length);await page.close();}
await context.close();}
const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}});const rp=await reduced.newPage();await rp.goto('http://127.0.0.1:4173/');await rp.waitForTimeout(1500);const reducedMotion=await rp.locator('.blu-intro').evaluate(e=>({height:e.offsetHeight,handDisplay:getComputedStyle(document.querySelector('.blu-hand')).display}));await reduced.close();await browser.close();await fs.writeFile('evidence/browser-validation.json',JSON.stringify({testedAt:new Date().toISOString(),results,reducedMotion,submissions:'No live form was submitted.'},null,2));
