// Uses Git's configured credential helper; credentials stay in process memory.
import{execFileSync}from'node:child_process';import fs from'node:fs/promises';
const repo='bdteamditto/BLU',mode=process.argv[2]||'status';
const credential=execFileSync('git',['credential','fill'],{input:'protocol=https\nhost=github.com\n\n',encoding:'utf8',stdio:['pipe','pipe','pipe']});
const token=credential.split('\n').find(line=>line.startsWith('password='))?.slice(9);if(!token)throw Error('Git credential helper returned no authenticated credential.');
async function api(endpoint,method='GET',body){const r=await fetch('https://api.github.com/repos/'+repo+endpoint,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>null);return{status:r.status,data};}
if(mode==='allow-preview'){const existing=await api('/environments/github-pages/deployment-branch-policies');if(existing.data?.branch_policies?.some(p=>p.name==='preview'))console.log('Preview policy already present');else{const r=await api('/environments/github-pages/deployment-branch-policies','POST',{name:'preview',type:'branch'});console.log('Preview policy',r.status,r.data?.name||r.data?.message);if(r.status>=400)process.exitCode=1;}}
else if(mode==='debug'){const job=await api('/actions/jobs/113253803089');console.log('Job',job.data);const checks=job.data?.check_run_url;if(checks){const id=checks.split('/').pop();console.log('Annotations',(await api('/check-runs/'+id+'/annotations')).data);}console.log('Environment',(await api('/environments/github-pages')).data);}
else if(mode==='setup'){let r=await api('/pages');if(r.status===404)r=await api('/pages','POST',{build_type:'workflow'});if(r.status>=400){console.log('Pages setup failed',r.status,r.data?.message);process.exitCode=1;}else console.log('Pages configured',r.data?.html_url,r.data?.build_type);}
else{const runs=await api('/actions/runs?branch=preview&per_page=3');console.log(JSON.stringify(runs.data?.workflow_runs?.map(r=>({id:r.id,status:r.status,conclusion:r.conclusion,url:r.html_url,sha:r.head_sha})),null,2));const pages=await api('/pages');console.log('Pages',pages.status,pages.data?.html_url,pages.data?.status);await fs.writeFile('evidence/deployment-status.json',JSON.stringify({checkedAt:new Date().toISOString(),runs:runs.data?.workflow_runs?.map(r=>({id:r.id,status:r.status,conclusion:r.conclusion,url:r.html_url,sha:r.head_sha})),pages:{status:pages.status,url:pages.data?.html_url,buildStatus:pages.data?.status}},null,2));}
