import fs from'node:fs/promises';import crypto from'node:crypto';import{load}from'cheerio';
const m=JSON.parse(await fs.readFile('evidence/manifest.json','utf8'));
export function signature(html){const $=load(html);$('script,style,#blu-intro-root,#blu-ecosystem-root').remove();const texts=[];
function walk(el){if(el.type==='text'){const text=el.data.replace(/\s+/g,' ').trim();if(text)texts.push(text);}else for(const c of el.children||[])walk(c);}walk($('body')[0]);
const links=$('body a[href]').map((_,e)=>({text:$(e).text().replace(/\s+/g,' ').trim(),href:$(e).attr('href')})).get();
const forms=$('form').map((_,e)=>({action:$(e).attr('action')||'',method:$(e).attr('method')||'',fields:$(e).find('input,textarea,select,button').map((_,f)=>({tag:f.name,type:$(f).attr('type')||'',name:$(f).attr('name')||'',value:$(f).attr('value')||'',placeholder:$(f).attr('placeholder')||'',required:$(f).attr('required')!==undefined,options:$(f).find('option').map((_,o)=>({value:$(o).attr('value'),text:$(o).text()})).get()})).get()})).get();
const numbers=texts.join(' ').match(/\d[\d,.]*/g)||[];return{texts,links,forms,numbers};}
if(process.argv[1]?.endsWith('validate.mjs')){const results=[];for(const p of m.pages){const source=await fs.readFile(`evidence/source/${p.key}.html`,'utf8'),file=p.path==='/'?'dist/index.html':'dist'+p.path+'index.html',render=await fs.readFile(file,'utf8'),a=signature(source),b=signature(render);const differences=[];for(const field of Object.keys(a))if(JSON.stringify(a[field])!==JSON.stringify(b[field]))differences.push({field,sourceCount:a[field].length,renderedCount:b[field].length,firstDifference:a[field].findIndex((v,i)=>JSON.stringify(v)!==JSON.stringify(b[field][i]))});results.push({path:p.path,capturedAt:p.capturedAt,sourceHash:crypto.createHash('sha256').update(source).digest('hex'),textNodes:a.texts.length,links:a.links.length,forms:a.forms.length,numbers:a.numbers.length,pass:!differences.length,differences});}
await fs.writeFile('evidence/content-validation.json',JSON.stringify({testedAt:new Date().toISOString(),scope:'Static source vs built HTML. Whitespace normalized only. Does not certify image text, visual visibility or backend submissions.',results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;}
